/**
 * Asset resolution + manifest seam.
 *
 * The renderer falls back to procedural tiles for any symbol without art, so the
 * manifest can hold as little or as much as exists. This module is the seam art
 * plugs into: declare assets in {@link ASSET_MANIFEST}, resolve their URLs with
 * {@link assetUrl} (CDN base + cache-busting). At boot the loader
 * (`core/assetLoader.ts`) loads the manifest through Pixi `Assets`, and the
 * renderer prefers a loaded texture over its procedural tile — so adding or
 * swapping art is a pure data change. The missing-asset guard in
 * `assets.test.ts` fails CI if a declared bundle-relative asset isn't present
 * under `frontend/public/`.
 *
 * @example
 * # .env.production
 * VITE_ASSET_BASE=https://cdn.stake-engine.com/novaforged
 * VITE_ASSET_VERSION=1.1.0
 */
const RAW_BASE = import.meta.env.VITE_ASSET_BASE ?? '';

/** Normalized asset base URL (no trailing slash). Empty means "bundle-relative". */
export const ASSET_BASE = RAW_BASE.replace(/\/$/, '');

/** Cache-busting version appended to CDN asset URLs (empty in dev). */
export const ASSET_VERSION = (import.meta.env.VITE_ASSET_VERSION ?? '').trim();

/**
 * Resolve an asset path against the configured base, with cache-busting.
 * @param path Path relative to the asset root (e.g. `"audio/spin.mp3"`).
 */
export function assetUrl(path: string): string {
  const clean = path.replace(/^\//, '');
  const url = ASSET_BASE ? `${ASSET_BASE}/${clean}` : clean;
  // Only cache-bust CDN-served assets; bundle-relative ones are already hashed.
  return ASSET_BASE && ASSET_VERSION ? `${url}?v=${encodeURIComponent(ASSET_VERSION)}` : url;
}

/** A declared asset group: a logical preload bucket (e.g. boot vs feature). */
export interface AssetGroup {
  /** Group name used to phase loading (e.g. `"boot"`, `"freespins"`). */
  name: string;
  /** Asset keys → paths (relative to the asset root). */
  assets: Record<string, string>;
}

/**
 * Declared assets, grouped by preload phase. Keyed by the same id the renderer
 * asks for (`symbol:<id>`); resolved via {@link assetUrl} and verified to ship
 * by the missing-asset guard in `assets.test.ts`.
 *
 * The symbol tiles here are **placeholder** neon-cosmic art (vector, generated by
 * `scripts/gen-placeholder-art.mjs`) shared across all three games — they share
 * the same symbol ids. Swapping in a designer's final art is a pure file
 * replacement under `public/symbols/`; no code changes.
 */
export const ASSET_MANIFEST: readonly AssetGroup[] = [
  {
    name: 'symbols',
    assets: {
      'symbol:W': 'symbols/W.svg',
      'symbol:S': 'symbols/S.svg',
      'symbol:H1': 'symbols/H1.svg',
      'symbol:H2': 'symbols/H2.svg',
      'symbol:H3': 'symbols/H3.svg',
      'symbol:H4': 'symbols/H4.svg',
      'symbol:L1': 'symbols/L1.svg',
      'symbol:L2': 'symbols/L2.svg',
      'symbol:L3': 'symbols/L3.svg',
      'symbol:L4': 'symbols/L4.svg',
      'symbol:L5': 'symbols/L5.svg',
    },
  },
];

/** Flat list of every declared asset URL (for preload / CI verification). */
export function manifestUrls(): string[] {
  return ASSET_MANIFEST.flatMap((g) => Object.values(g.assets)).map(assetUrl);
}

/**
 * Flat list of every declared asset *path* (relative to the asset root, before
 * {@link assetUrl} resolution). Bundle-relative paths (no {@link ASSET_BASE})
 * are served from `frontend/public/<path>`; the missing-asset guard in
 * `assets.test.ts` checks each one exists so a dangling reference fails CI.
 */
export function manifestPaths(): string[] {
  return ASSET_MANIFEST.flatMap((g) => Object.values(g.assets));
}

/** True when assets resolve from the bundle (`public/`) rather than a CDN. */
export const ASSET_IS_BUNDLE_RELATIVE = ASSET_BASE === '';
